In [1]:
import numpy as np

In [2]:
np.sqrt(255)

15.968719422671311

# Arrays

## np.array()

In [4]:
a = [1,2,3,4]
type(a)

list

In [5]:
type(np.array(a))

numpy.ndarray

## np.arange()

In [7]:
b = np.arange(4, 24, 2)
print(b)

[ 4  6  8 10 12 14 16 18 20 22]


## np.linespace()

In [14]:
c = np.linspace(1,50, 9)
c

array([ 1.   ,  7.125, 13.25 , 19.375, 25.5  , 31.625, 37.75 , 43.875,
       50.   ])

## np.zeros() y np.ones()

In [15]:
d = np.zeros(50)
d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
e = np.ones(50)
e

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Dimensiones

In [28]:
array_2d = np.array([d,e])
array_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.]])

## array.shape

In [20]:
array_2d.shape

(2, 50)

## array.size

In [21]:
array_2d.size

100

## array.ndim

In [23]:
array_2d.ndim

2

## Operaciones con Arrays

In [24]:
lista_1 = [1,2,3]
lista_2 = [4,5,6]

In [25]:
array_1 = np.array(lista_1)
array_2 = np.array(lista_2)

In [26]:
array_1 * array_2

array([ 4, 10, 18])

# Funciones

## np.reshape()

In [30]:
array_2d.shape

(2, 50)

In [32]:
f = np.reshape(array_2d, (1,100))
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

## array.T

In [36]:
a = np.array([[1,2,3],[4,5,6]])
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## np.random

### np.random.randint()

In [37]:
np.random.randint(1,500)

313

## np.where()

In [38]:
np.where(array_2d == 1, array_2d * 10, array_2d - 5)

array([[-5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

# Estadistica

## Distribuciones

In [40]:
array_normal = np.random.normal(1.75, 0.05, 1000)
array_normal

array([1.67212641, 1.74432007, 1.72510167, 1.7614405 , 1.80506967,
       1.75334071, 1.73979423, 1.77412351, 1.70102346, 1.77037432,
       1.74177804, 1.73165151, 1.81526998, 1.81007603, 1.75023857,
       1.77303155, 1.71583869, 1.67603262, 1.73231058, 1.79454249,
       1.77937977, 1.82849045, 1.75127633, 1.79144276, 1.65488472,
       1.76029224, 1.80084966, 1.73964929, 1.70439368, 1.77435442,
       1.77744925, 1.78396471, 1.70623327, 1.74523698, 1.74703144,
       1.66921968, 1.76203912, 1.80064817, 1.81204448, 1.82212633,
       1.82383404, 1.77843218, 1.73982572, 1.73371445, 1.72674519,
       1.77529708, 1.72315043, 1.74169099, 1.70699035, 1.73692032,
       1.73524301, 1.79860386, 1.65134329, 1.77589767, 1.75344936,
       1.69735997, 1.67328954, 1.79546444, 1.71858579, 1.7647367 ,
       1.79805375, 1.73653657, 1.71665345, 1.72964564, 1.79706282,
       1.76658935, 1.76122524, 1.73294389, 1.80700152, 1.80851903,
       1.72331539, 1.6466548 , 1.64440538, 1.75982089, 1.82949

## np.mean()

In [41]:
np.mean(array_normal)

1.7497976227132352

## np.median()

In [42]:
np.median(array_normal)

1.748738355298477

## np.std()

In [43]:
np.std(array_normal)

0.048760204648014026